# **1. EXPLORATRY DATA ANALYSIS**

In [ ]:
import pandas as pd # importing pandas library

In [ ]:
data = pd.read_csv('data\MDT32_final_project_dataset.csv') # original dataset read
df = pd.DataFrame(data) # converting to dataframe
df.head() # show first 5 rows

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target Failure Type  
0                    1551         42.8                0       0   No Failure  
1                    1408         46.3                3       0   No Failure  
2                    1498         49.4                5       0   No Failure  
3                    1433         39.5                7       0   No Failure  
4                    1408         40.0                9       0   No Failure

In [ ]:
df.shape # no.of rows, no.of columns

(10000, 10)

In [ ]:
df.size #n.of data points

100000

In [ ]:
df.info() #about data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   UDI                      10000 non-null  int64  
 1   Product ID               10000 non-null  object 
 2   Type                     10000 non-null  object 
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64  
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64  
 8   Target                   10000 non-null  int64  
 9   Failure Type             10000 non-null  object 
dtypes: float64(3), int64(4), object(3)
memory usage: 781.4+ KB


In [ ]:
df.describe() #describe data in statistic

UDI  Air temperature [K]  Process temperature [K]  \
count  10000.00000         10000.000000             10000.000000   
mean    5000.50000           300.004930               310.005560   
std     2886.89568             2.000259                 1.483734   
min        1.00000           295.300000               305.700000   
25%     2500.75000           298.300000               308.800000   
50%     5000.50000           300.100000               310.100000   
75%     7500.25000           301.500000               311.100000   
max    10000.00000           304.500000               313.800000   

       Rotational speed [rpm]   Torque [Nm]  Tool wear [min]        Target  
count            10000.000000  10000.000000     10000.000000  10000.000000  
mean              1538.776100     39.986910       107.951000      0.033900  
std                179.284096      9.968934        63.654147      0.180981  
min               1168.000000      3.800000         0.000000      0.000000  
25%               1423.000000     33.200000        53.000000      0.000000  
50%               1503.000000     40.100000       108.000000      0.000000  
75%               1612.000000     46.800000       162.000000      0.000000  
max               2886.000000     76.600000       253.000000      1.000000

## **NULL VALUE CHECKING**

In [ ]:
df.isnull().sum() #checking any null values

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Target                     0
Failure Type               0
dtype: int64

In [ ]:
df_columns = df.columns

In [ ]:
udi_col = df[df_columns[0]].value_counts().reset_index() #checking duplicate in UDI column
udi_col

UDI  count
0         1      1
1      6671      1
2      6664      1
3      6665      1
4      6666      1
...     ...    ...
9995   3334      1
9996   3335      1
9997   3336      1
9998   3337      1
9999  10000      1

[10000 rows x 2 columns]

In [ ]:
udi_col[udi_col['count'] > 1] # UDI is unique column

Empty DataFrame
Columns: [UDI, count]
Index: []

In [ ]:
product_col = df[df_columns[1]].value_counts().reset_index() #checking duplicate in Product ID column
product_col

Product ID  count
0        M14860      1
1        L53850      1
2        L53843      1
3        L53844      1
4        L53845      1
...         ...    ...
9995     M18193      1
9996     M18194      1
9997     L50515      1
9998     L50516      1
9999     M24859      1

[10000 rows x 2 columns]

In [ ]:
product_col[product_col['count']>1] # Product ID is unique column

Empty DataFrame
Columns: [Product ID, count]
Index: []

In [ ]:
type_col = df[df_columns[2]].value_counts().reset_index() #checking duplicate in Type column, Type is category column
type_col

Type  count
0    L   6000
1    M   2997
2    H   1003

In [ ]:
df[df_columns[3]].value_counts().reset_index() #checking duplicate in Air temperature [K] column, Air temperature [K] is continous value column

Air temperature [K]  count
0                 300.7    279
1                 298.9    231
2                 297.4    230
3                 300.5    229
4                 298.8    227
..                  ...    ...
88                304.4      7
89                296.0      6
90                295.4      3
91                295.3      3
92                304.5      1

[93 rows x 2 columns]

In [ ]:
df[df_columns[4]].value_counts().reset_index() #checking duplicate in Process temperature [K] column, Process temperature [K] is continous value column

Process temperature [K]  count
0                     310.6    317
1                     310.8    273
2                     310.7    266
3                     308.6    265
4                     310.5    263
..                      ...    ...
77                    306.9      4
78                    313.7      4
79                    305.8      3
80                    305.7      2
81                    313.8      2

[82 rows x 2 columns]

In [ ]:
df[df_columns[5]].value_counts().reset_index() #checking duplicate in Rotational speed [rpm] column, Rotational speed [rpm] is continous value column

Rotational speed [rpm]  count
0                      1452     48
1                      1435     43
2                      1447     42
3                      1429     40
4                      1469     40
..                      ...    ...
936                    2197      1
937                    2211      1
938                    1905      1
939                    1893      1
940                    2450      1

[941 rows x 2 columns]

In [ ]:
df[df_columns[6]].value_counts().reset_index() #checking duplicate in Torque [Nm] column, Torque [Nm] is continous value column

Torque [Nm]  count
0           40.2     52
1           38.5     50
2           42.4     50
3           35.8     50
4           37.7     49
..           ...    ...
572         65.7      1
573         67.8      1
574         16.0      1
575          4.6      1
576         15.5      1

[577 rows x 2 columns]

In [ ]:
df[df_columns[7]].value_counts().reset_index() #checking duplicate in Tool wear [min] column, Tool wear [min] is continous value column

Tool wear [min]  count
0                  0    120
1                  2     69
2                  5     63
3                  7     58
4                 59     58
..               ...    ...
241              237      1
242              239      1
243              241      1
244              251      1
245              253      1

[246 rows x 2 columns]

In [ ]:
df[df_columns[8]].value_counts().reset_index() # 0 - No Failure 1 - Failure Binary class

Target  count
0       0   9661
1       1    339

In [ ]:
df[df_columns[9]].value_counts().reset_index() # Failure Type is category column and multi class

Failure Type  count
0                No Failure   9652
1  Heat Dissipation Failure    112
2             Power Failure     95
3        Overstrain Failure     78
4         Tool Wear Failure     45
5           Random Failures     18

category columns
  1.product type
  2.Target
  3.Failure Type

Unique columns
  1.UDI
  2.Product ID

continous value column
  1.Air temperature [K]
  2.Process temperature [K]
  3.Rotational speed [rpm]
  4.Torque [Nm]
  5.Tool wear [min]

● air temperature [K]: generated using a random walk process later normalized to a standard
deviation of 2 K around 300 K

● process temperature [K]: generated using a random walk process normalized to a standard
deviation of 1 K, added to the air temperature plus 10 K.

In [ ]:
air = df['Air temperature [K]'][0].round(0)  # air temperature
process = df['Process temperature [K]'][0].round(0) # process temperature
print('air = ',air)
print('process = ', process)
if (process - 10) == air:
  print('yes, Process air temperatue - 10  = air tempearture')

air =  298.0
process =  309.0


## **CORELATOIN**

In [ ]:
import plotly.express as px
corelation = df[['Air temperature [K]','Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]','Target']].corr()
fig = px.imshow(corelation.round(1),
          text_auto = True,
          title = 'Corelation Chart')
fig.show()

## **OUTLIERS**

In [ ]:
import plotly.express as px
outlier_df = df[['Air temperature [K]','Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]']]
for i in list(outlier_df.columns):
  fig2 = px.box(
      data_frame = outlier_df,
      x = i
  )
  fig2.show()

## **DATA DISTRIBUTION**

In [ ]:
import plotly.figure_factory as ff
columns = ['Air temperature [K]','Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]']
for i in columns:
  fig = ff.create_distplot(hist_data = list([df[i]]),
                           group_labels=[i],
                           bin_size = 0.4,
                           curve_type = "normal",
                           show_rug = False
                          )
  fig.show(title = f'{i} data Distribution')

## **EDA ON TYPE**

In [ ]:
import plotly.express as px
eda1 = df['Type'].value_counts().reset_index()
fig1 = px.bar(
        data_frame = eda1,
        x = 'Type',
        y = 'count',
        title = 'Quality variant',
        color = 'Type',
        text_auto = True
        )
fig1.show()

In [ ]:
df1 = df.groupby(['Type'])[['Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]']].max().reset_index()
df1

Type  Process temperature [K]  Rotational speed [rpm]  Torque [Nm]  \
0    H                    313.5                    2636         72.8   
1    L                    313.8                    2886         76.6   
2    M                    313.8                    2710         76.2   

   Tool wear [min]  
0              246  
1              251  
2              253

In [ ]:
df2 = df.groupby(['Type'])[['Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]']].min().reset_index()
df2

Type  Process temperature [K]  Rotational speed [rpm]  Torque [Nm]  \
0    H                    305.9                    1212         12.8   
1    L                    305.7                    1181          3.8   
2    M                    305.7                    1168          9.7   

   Tool wear [min]  
0                0  
1                0  
2                0

In [ ]:
df3 = df.groupby(['Type'])[['Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]']].mean().reset_index()
df3

Type  Process temperature [K]  Rotational speed [rpm]  Torque [Nm]  \
0    H               309.925723             1538.147557    39.838285   
1    L               310.012300             1539.469167    39.996600   
2    M               310.018785             1537.598932    40.017251   

   Tool wear [min]  
0       107.419741  
1       108.378833  
2       107.272272

In [ ]:
df4 = df.groupby(['Type'])['Target'].sum().reset_index()
fig2 = px.pie(data_frame = df4,
              names = 'Type',
              values = 'Target',
              title = 'Product VS Failure',
              color = 'Type')
fig2.show()

In [ ]:
pecentage_product_fail = df.groupby(['Type'])[['Type', 'Target']].value_counts().reset_index()

In [ ]:
for i in ['H','M','L']:
  no_failure_count = pecentage_product_fail[(pecentage_product_fail['Type']==i) & (pecentage_product_fail['Target']==0)]['count'].values[0]
  failure_count = pecentage_product_fail[(pecentage_product_fail['Type']==i) & (pecentage_product_fail['Target']==1)]['count'].values[0]
  total = failure_count + no_failure_count
  perentage = ((failure_count / no_failure_count) * 100).round(2)

  p_df = {'name':['No Fail', 'Fail'],'value':[no_failure_count,failure_count]}
  fig4 = px.pie(p_df, names = 'name', values='value', color = 'name',title = f'{i} - No Failure VS Failure')
  fig4.show()

In [ ]:
df5 = df[df['Failure Type'] != 'No Failure'].groupby('Type')['Failure Type'].value_counts().reset_index().sort_values(by = ['count'])
fig3 = px.bar(data_frame = df5,
              x = 'Type',
              y = 'count',
              title = 'Product VS Failure Type',
              color = 'Failure Type',
              barmode = 'group')
fig3.show()

In [ ]:
px.histogram(data_frame = df['Rotational speed [rpm]'],
             x = 'Rotational speed [rpm]')

## **EDA ON TORQUE COLUMN**

In [ ]:
fig5 = px.scatter(data_frame = df,
                  x = 'Torque [Nm]',
                  y = 'Rotational speed [rpm]',
                  title = 'Torque vs Speed',
                  hover_data='Type')
fig5.show()

In [ ]:
t_vs_t = df[(eda_df['Target']==1)].groupby(['Torque [Nm]'])['Target'].sum().reset_index()
t_vs_t

Torque [Nm]  Target
0           23.4       1
1           25.6       1
2           27.0       1
3           27.3       1
4           28.9       1
..           ...     ...
176         65.9       1
177         66.3       1
178         66.7       2
179         66.8       2
180         67.2       1

[181 rows x 2 columns]

In [ ]:
fig7 = px.histogram(data_frame = t_vs_t,
                    x = 'Torque [Nm]',
                    y = 'Target',
                    title = 'Torque vs Target')
fig7.show()

## **EDA ON ROTATIONAL SPEED COLUMN**

In [ ]:
# EDA ON TORQUE COLUMN
fig8 = px.scatter(data_frame = df,
                  x = 'Rotational speed [rpm]',
                  y = 'Torque [Nm]',
                  title = 'SPEED vs TORQUE',
                  hover_data='Type')
fig8.show()

# **2. FEATURE ENGINEERING**

● rotational speed [rpm]: calculated from power of 2860 W, overlaid with a normally
distributed noise

In [ ]:
# noise power
import math
rpm = df['Rotational speed [rpm]'][9999]
torque = df['Torque [Nm]'][9999]
power = (2*math.pi*rpm*torque)/60          # out put power calculation formula = (2*pi*N*T)/60
power

6314.601233715484

In [ ]:
df['Power'] = 2860             # creating  power column

In [ ]:
for i in range(df.shape[0]):
  rpm = df['Rotational speed [rpm]'][i]
  torque = df['Torque [Nm]'][i]
  df.loc[i,'Noise Power'] = (2*math.pi*rpm*torque)/60       # creating

In [ ]:
df['Noise'] = df['Noise Power'] - df['Power']

In [ ]:
df.head()

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target Failure Type  \
0                    1551         42.8                0       0   No Failure   
1                    1408         46.3                3       0   No Failure   
2                    1498         49.4                5       0   No Failure   
3                    1433         39.5                7       0   No Failure   
4                    1408         40.0                9       0   No Failure   

   Power  Noise Power        Noise  
0   2860  6951.590560  4091.590560  
1   2860  6826.722724  3966.722724  
2   2860  7749.387543  4889.387543  
3   2860  5927.504659  3067.504659  
4   2860  5897.816608  3037.816608

In [ ]:
df['Difference Temperature'] = (df['Process temperature [K]'] - df['Air temperature [K]'])/2

In [ ]:
df.head(5)

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target Failure Type  \
0                    1551         42.8                0       0   No Failure   
1                    1408         46.3                3       0   No Failure   
2                    1498         49.4                5       0   No Failure   
3                    1433         39.5                7       0   No Failure   
4                    1408         40.0                9       0   No Failure   

   Power  Noise Power        Noise  Difference Temperature  
0   2860  6951.590560  4091.590560                    5.25  
1   2860  6826.722724  3966.722724                    5.25  
2   2860  7749.387543  4889.387543                    5.20  
3   2860  5927.504659  3067.504659                    5.20  
4   2860  5897.816608  3037.816608                    5.25

In [ ]:
df = df.drop(columns = ['Power'], axis = 1)

In [ ]:
df.head(5)

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target Failure Type  \
0                    1551         42.8                0       0   No Failure   
1                    1408         46.3                3       0   No Failure   
2                    1498         49.4                5       0   No Failure   
3                    1433         39.5                7       0   No Failure   
4                    1408         40.0                9       0   No Failure   

   Noise Power        Noise  Difference Temperature  
0  6951.590560  4091.590560                    5.25  
1  6826.722724  3966.722724                    5.25  
2  7749.387543  4889.387543                    5.20  
3  5927.504659  3067.504659                    5.20  
4  5897.816608  3037.816608                    5.25

In [ ]:
df.head(5)

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target Failure Type  \
0                    1551         42.8                0       0   No Failure   
1                    1408         46.3                3       0   No Failure   
2                    1498         49.4                5       0   No Failure   
3                    1433         39.5                7       0   No Failure   
4                    1408         40.0                9       0   No Failure   

   Noise Power    Noise  Difference Temperature  
0      6951.59  4091.59                    5.25  
1      6826.72  3966.72                    5.25  
2      7749.39  4889.39                    5.20  
3      5927.50  3067.50                    5.20  
4      5897.82  3037.82                    5.25

In [ ]:
df[['Noise Power','Noise']] = df[['Noise Power','Noise']].round(2)
df['Rotation per torque'] = df['Rotational speed [rpm]']/df['Torque [Nm]']
df['Torque per Rotation'] = df['Torque [Nm]']/df['Rotational speed [rpm]']
df['Tool wear per Rotation'] = df['Tool wear [min]']/df['Rotational speed [rpm]']
df['Tool wear per torque'] = df['Tool wear [min]']/df['Torque [Nm]']
df['Tool wear per power'] = df['Tool wear [min]']/df['Noise Power']

In [ ]:
df.shape

(10000, 18)

In [ ]:
df.head()

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target Failure Type  \
0                    1551         42.8                0       0   No Failure   
1                    1408         46.3                3       0   No Failure   
2                    1498         49.4                5       0   No Failure   
3                    1433         39.5                7       0   No Failure   
4                    1408         40.0                9       0   No Failure   

   Noise Power    Noise  Difference Temperature  Rotation per torque  \
0      6951.59  4091.59                    5.25            36.238318   
1      6826.72  3966.72                    5.25            30.410367   
2      7749.39  4889.39                    5.20            30.323887   
3      5927.50  3067.50                    5.20            36.278481   
4      5897.82  3037.82                    5.25            35.200000   

   Torque per Rotation  Tool wear per Rotation  Tool wear per torque  \
0             0.027595                0.000000              0.000000   
1             0.032884                0.002131              0.064795   
2             0.032977                0.003338              0.101215   
3             0.027565                0.004885              0.177215   
4             0.028409                0.006392              0.225000   

   Tool wear per power  
0             0.000000  
1             0.000439  
2             0.000645  
3             0.001181  
4             0.001526

In [ ]:
inconsistency_data = df[(df['Target'] == 1)&(df['Failure Type']=='No Failure')]

In [ ]:
df = df.drop(inconsistency_data.index)

In [ ]:
df[(df['Target'] == 1)  & (df['Failure Type']=='No Failure')]

Empty DataFrame
Columns: [Unnamed: 0, UDI, Product ID, Type, Air temperature [K], Process temperature [K], Rotational speed [rpm], Torque [Nm], Tool wear [min], Target, Failure Type, Noise Power, Noise, Difference Temperature, Rotation per torque, Torque per Rotation, Tool wear per Rotation, Tool wear per torque, Tool wear per power]
Index: []

In [ ]:
df[df['Failure Type']=='Random Failures'].shape

(18, 19)

In [ ]:
counts = 0
for i in range(df.shape[0]):
  if (df.loc[i,'Target'] == 0) & (df.loc[i,'Failure Type'] == 'Random Failures'):
    counts = counts + 1
print(counts)

18


In [ ]:
df.to_csv('fp_data_out.csv')

** MACHINE LEARNING**

In [ ]:
import pandas as pd
data = pd.read_csv('fp_data_out.csv')
df = pd.DataFrame(data)
df

Unnamed: 0    UDI Product ID Type  Air temperature [K]  \
0              0      1     M14860    M                298.1   
1              1      2     L47181    L                298.2   
2              2      3     L47182    L                298.1   
3              3      4     L47183    L                298.2   
4              4      5     L47184    L                298.2   
...          ...    ...        ...  ...                  ...   
9995        9995   9996     M24855    M                298.8   
9996        9996   9997     H39410    H                298.9   
9997        9997   9998     M24857    M                299.0   
9998        9998   9999     H39412    H                299.0   
9999        9999  10000     M24859    M                299.0   

      Process temperature [K]  Rotational speed [rpm]  Torque [Nm]  \
0                       308.6                    1551         42.8   
1                       308.7                    1408         46.3   
2                       308.5                    1498         49.4   
3                       308.6                    1433         39.5   
4                       308.7                    1408         40.0   
...                       ...                     ...          ...   
9995                    308.4                    1604         29.5   
9996                    308.4                    1632         31.8   
9997                    308.6                    1645         33.4   
9998                    308.7                    1408         48.5   
9999                    308.7                    1500         40.2   

      Tool wear [min]  Target Failure Type  Noise Power    Noise  \
0                   0       0   No Failure      6951.59  4091.59   
1                   3       0   No Failure      6826.72  3966.72   
2                   5       0   No Failure      7749.39  4889.39   
3                   7       0   No Failure      5927.50  3067.50   
4                   9       0   No Failure      5897.82  3037.82   
...               ...     ...          ...          ...      ...   
9995               14       0   No Failure      4955.13  2095.13   
9996               17       0   No Failure      5434.70  2574.70   
9997               22       0   No Failure      5753.62  2893.62   
9998               25       0   No Failure      7151.10  4291.10   
9999               30       0   No Failure      6314.60  3454.60   

      Difference Temperature  Rotation per torque  Torque per Rotation  \
0                       5.25            36.238318             0.027595   
1                       5.25            30.410367             0.032884   
2                       5.20            30.323887             0.032977   
3                       5.20            36.278481             0.027565   
4                       5.25            35.200000             0.028409   
...                      ...                  ...                  ...   
9995                    4.80            54.372881             0.018392   
9996                    4.75            51.320755             0.019485   
9997                    4.80            49.251497             0.020304   
9998                    4.85            29.030928             0.034446   
9999                    4.85            37.313433             0.026800   

      Tool wear per Rotation  Tool wear per torque  Tool wear per power  
0                   0.000000              0.000000             0.000000  
1                   0.002131              0.064795             0.000439  
2                   0.003338              0.101215             0.000645  
3                   0.004885              0.177215             0.001181  
4                   0.006392              0.225000             0.001526  
...                      ...                   ...                  ...  
9995                0.008728              0.474576             0.002825  
9996                0.010417              0.534591             0.003128  
9997                0.01

In [ ]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier,AdaBoostClassifier,VotingClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,roc_curve,roc_auc_score, auc,classification_report
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE,RandomOverSampler
import numpy as np
from scipy.stats import uniform, randint
import pandas as pd
from sklearn.feature_selection import chi2,f_classif,SelectKBest,SelectPercentile,mutual_info_classif, RFE
import pickle as pkl

In [ ]:
logistic_model = LogisticRegression()
K_neighbor_model = KNeighborsClassifier()
decision_tree_model = DecisionTreeClassifier()
random_forest_model = RandomForestClassifier()
gbc_model = GradientBoostingClassifier()
adaboost_model = AdaBoostClassifier(estimator = DecisionTreeClassifier(), n_estimators = 200,learning_rate=1)
models = [logistic_model,K_neighbor_model,decision_tree_model,random_forest_model,gbc_model,adaboost_model]

In [ ]:
df.columns

Index(['Unnamed: 0', 'UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Target', 'Failure Type', 'Noise Power', 'Noise',
       'Difference Temperature', 'Rotation per torque', 'Torque per Rotation',
       'Tool wear per Rotation', 'Tool wear per torque',
       'Tool wear per power'],
      dtype='object')

# **3. BINARY CLASSIFICATION TARGET**

In [ ]:
label_encoder = LabelEncoder()

X = df.drop(columns = ['Target','Failure Type','Product ID','UDI','Unnamed: 0'], axis=1)
X['Type'] = LabelEncoder().fit_transform(df['Type'])

y = df['Target']

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.20, random_state=100,stratify = y)
print(len(X_train),len(X_test),len(y_train),len(y_test))

8000 2000 8000 2000


## **MODEL SELECTION**

In [ ]:
from imblearn.over_sampling import SMOTE
evaluation_test = []
evaluation_train =[]
#logistic model
for model in models:

    print('model name =', model)
    #model train
    X_sampled,y_sampled = SMOTE().fit_resample(X_train,y_train)
    model.fit(X_sampled,y_sampled)

    # model prediction
    y_pred_test = model.predict(X_test)

    #model evaluation on test data
    test_accuracy = accuracy_score(y_test,y_pred_test)
    test_precision_score = precision_score(y_test,y_pred_test)
    test_recall_score = recall_score(y_test,y_pred_test)
    test_f1_score = f1_score(y_test,y_pred_test)
    test_conf_matrix = confusion_matrix(y_test,y_pred_test)
    tn, fp, fn, tp = confusion_matrix(y_test,y_pred_test).ravel()
    specificity_test = (tn/(fp+tn))

    print('Testing Evaluation--------------------------------------------------------------------')
    print('test_accuracy',test_accuracy)
    print('test_precision_score',test_precision_score)
    print('test_recall_score',test_recall_score)
    print('test_f1_score',test_f1_score)
    print('test_conf_matrix',test_conf_matrix)
    print('specificity_test: ',specificity_test)

    # Plot ROC curve
    y_prob_test = model.predict_proba(X_test)[:,1]
    fpr,tpr,thershold = roc_curve(y_test, y_prob_test)
    roc_auc = auc(fpr, tpr)

    plt.figure()
    plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic')
    plt.legend(loc="lower right")
    print('roc_auc',roc_auc)
    plt.show()

    data_test={'model name': model,
              'test_accuracy':test_accuracy,
              'test_precision_score':test_precision_score,
              'test_recall_score':test_recall_score,
              'test_f1_score':test_f1_score,
              'test_conf_matrix':str(test_conf_matrix),
              'roc_auc':roc_auc}

    evaluation_test.append(data_test)

    #model evaluation in train data
    y_pred_train = model.predict(X_train)

    train_accuracy = accuracy_score(y_train,y_pred_train)
    train_precision_score = precision_score(y_train,y_pred_train)
    train_recall_score = recall_score(y_train,y_pred_train)
    train_f1_score = f1_score(y_train,y_pred_train)
    train_conf_matrix = confusion_matrix(y_train,y_pred_train)
    tn, fp, fn, tp = confusion_matrix(y_train,y_pred_train).ravel()
    specificity_train = (tn/(fp+tn))

    print('Training Evaluation--------------------------------------------------------------------')
    print('train_accuracy',train_accuracy)
    print('train_precision_score',train_precision_score)
    print('train_recall_score',train_recall_score)
    print('train_f1_score',train_f1_score)
    print('train_conf_matrix',train_conf_matrix)
    print('specificity_train: ',specificity_train)

    # Plot ROC curve
    y_prob_train = model.predict_proba(X_train)[:,1]
    fpr,tpr,thershold = roc_curve(y_train, y_prob_train)
    roc_auc_train = auc(fpr, tpr)

    plt.figure()
    plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc_train)
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic')
    plt.legend(loc="lower right")
    print('roc_auc_train',roc_auc_train)
    plt.show()
    data_train = {'model name' : model,
                'train_accuracy':train_accuracy,
                'train_precision_score':train_precision_score,
                'train_recall_score':train_recall_score,
                'train_f1_score':train_f1_score,
                'train_conf_matrix':str(train_conf_matrix),
                'train_roc_auc':roc_auc_train}
    evaluation_train.append(data_train)

In [ ]:
df_evaluation_test = pd.DataFrame(evaluation_test)
df_evaluation_train = pd.DataFrame(evaluation_train)

In [ ]:
df_evaluation_test

model name  test_accuracy  \
0                               LogisticRegression()       0.972237   
1                             KNeighborsClassifier()       0.974332   
2                           DecisionTreeClassifier()       0.983761   
3  (DecisionTreeClassifier(max_features='sqrt', r...       0.989523   
4  ([DecisionTreeRegressor(criterion='friedman_ms...       0.987428   
5  (DecisionTreeClassifier(max_depth=1, random_st...       0.973284   

   test_precision_score  test_recall_score  test_f1_score  \
0              0.555556           0.092593       0.158730   
1              0.777778           0.129630       0.222222   
2              0.725490           0.685185       0.704762   
3              0.972222           0.648148       0.777778   
4              0.875000           0.648148       0.744681   
5              0.551724           0.296296       0.385542   

              test_conf_matrix   roc_auc  
0  [[1851    4]\n [  49    5]]  0.895428  
1  [[1853    2]\n [  47    7]]  0.687836  
2  [[1841   14]\n [  17   37]]  0.838819  
3  [[1854    1]\n [  19   35]]  0.988290  
4  [[1850    5]\n [  19   35]]  0.990446  
5  [[1842   13]\n [  38   16]]  0.938894

## **HYPER PARAMETER TUNNING**

In [ ]:
# Base estimator
base_estimator = DecisionTreeClassifier()

# AdaBoost model
ada_model = AdaBoostClassifier(base_estimator=base_estimator)

param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.5, 1],
    'base_estimator__max_depth': [1, 2, 3, 4, 5],
    'base_estimator__min_samples_split': [2, 5, 10],
    'base_estimator__min_samples_leaf': [1, 2, 4],
}

random_search = RandomizedSearchCV(
    estimator=ada_model,
    param_distributions=param_grid,
    n_iter=20,  # Number of random combinations to try
    scoring='recall',  # Assuming recall is important
    cv=5,
    n_jobs=-1,  # Use all available cores
    verbose=2,
    random_state=42
)

X_sampled,y_sampled = SMOTE().fit_resample(X_train,y_train)
random_search.fit(X_sampled,y_sampled)
model = random_search.best_estimator_
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)
precision = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)
tn, fp, fn, tp = confusion_matrix(y_test,y_pred).ravel()
specificity = tn/(fp+tn)

print('accuracy = ',accuracy)
print('precision = ',precision)
print('recall = ',recall)
print('specificity = ',specificity)
print('f1 = ',f1)
print('conf_matrix = ',conf_matrix)

y_proba = model.predict_proba(X_test)[:,1]
fpr,tpr,thershold = roc_curve(y_test, y_proba)
auc_score = auc(fpr,tpr)

print('auc_score = ',auc_score)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:156: FutureWarning:

`base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.



accuracy =  0.9848088004190676
precision =  0.7551020408163265
recall =  0.6851851851851852
specificity =  0.9935309973045822
f1 =  0.7184466019417475
conf_matrix =  [[1843   12]
 [  17   37]]
auc_score =  0.9451532394928621


In [ ]:
random_search.best_params_

{'n_estimators': 200,
 'learning_rate': 0.1,
 'base_estimator__min_samples_split': 5,
 'base_estimator__min_samples_leaf': 4,
 'base_estimator__max_depth': 5}

## **MODEL EVALUATION**

In [ ]:
gbc = GradientBoostingClassifier(learning_rate=0.07243118882864871,
                                 max_depth=5,
                                 min_samples_split=8,
                                 n_estimators=230,
                                 random_state=100,
                                 subsample=0.995724756941474)

rfc = RandomForestClassifier(max_depth=5,
                             min_samples_leaf=9,
                             min_samples_split=5,
                             n_estimators=203,
                             random_state=100)



base_estimator = DecisionTreeClassifier(max_depth=5,
                                        min_samples_leaf=4,
                                        min_samples_split=5,
                                        random_state=100)

ada_model = AdaBoostClassifier(estimator = base_estimator,
                              n_estimators=200,
                              learning_rate= 0.1,
                              random_state =100)



ensemble_model = VotingClassifier(
    estimators=[
        ('Random forest classifier',rfc),
        ('Gradient Bossting Classifier',gbc),
        ('AdaBoostclassifier',ada_model)
        ],
        voting = 'soft'
)

X_sampled,y_sampled = SMOTE().fit_resample(X_train,y_train)
ensemble_smote = ensemble_model.fit(X_sampled,y_sampled)

X_sampled,y_sampled = RandomOverSampler().fit_resample(X_train,y_train)
ensmble_rose = ensemble_model.fit(X_sampled,y_sampled)

y_pred_smote = ensemble_smote.predict_proba(X_test)
y_pred_rose = ensmble_rose.predict_proba(X_test)

avr_proba = (y_pred_smote + y_pred_rose)/2
y_pred = np.argmax(avr_proba, axis =1)
#evaluation test data

accuracy = accuracy_score(y_test,y_pred)
precision = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)

#specificity
tn, fp, fn, tp = confusion_matrix(y_test,y_pred).ravel()
specificity = tn/(fp+tn)

# #roc curve
fpr,tpr,thershold = roc_curve(y_test, avr_proba[:,1])
auc_score = auc(fpr,tpr)

print('accuracy = ',accuracy)
print('precision = ',precision)
print('recall = ',recall)
print('specificity = ',specificity)
print('f1 = ',f1)
print('conf_matrix = ',conf_matrix)
print('auc_score = ',auc_score)

#training data testing

# print('Training Evaluation--------------------------------------------------------------------')
y_pred_train_smote = ensemble_smote.predict_proba(X_train)
y_pred_train_rose = ensmble_rose.predict_proba(X_train)

avr_proba_train = (y_pred_train_smote + y_pred_train_rose)/2
y_pred_train = np.argmax(avr_proba_train, axis =1)

# #evaluation train data

train_accuracy = accuracy_score(y_train,y_pred_train)
train_precision_score = precision_score(y_train,y_pred_train)
train_recall_score = recall_score(y_train,y_pred_train)
train_f1_score = f1_score(y_train,y_pred_train)
train_conf_matrix = confusion_matrix(y_train,y_pred_train)

#specificity
tn, fp, fn, tp = confusion_matrix(y_train,y_pred_train).ravel()
specificity_train = (tn/(fp+tn))

#roc curve
fpr,tpr,thershold = roc_curve(y_train, avr_proba_train[:,1])
roc_auc_train = auc(fpr, tpr)


print('train_accuracy',train_accuracy)
print('train_precision_score',train_precision_score)
print('train_recall_score',train_recall_score)
print('train_f1_score',train_f1_score)
print('train_conf_matrix',train_conf_matrix)
print('specificity_train: ',specificity_train)
print('roc_auc_train: ',roc_auc_train)

accuracy =  0.9879903923138511
precision =  0.8117647058823529
recall =  0.8313253012048193
specificity =  0.9933747412008281
f1 =  0.8214285714285715
conf_matrix =  [[2399   16]
 [  14   69]]
auc_score =  0.9952106562897554
train_accuracy 0.9998665421059656
train_precision_score 0.9959677419354839
train_recall_score 1.0
train_f1_score 0.997979797979798
train_conf_matrix [[7245    1]
 [   0  247]]
specificity_train:  0.9998619928236269
roc_auc_train:  1.0


In [ ]:
ensemble_smote
ensmble_rose

In [ ]:
with open ('model_smote.pkl','wb')as file:
  pkl.dump(ensemble_smote,file)

with open ('model_rose.pkl','wb')as file:
  pkl.dump(ensmble_rose,file)

In [ ]:
with open ('scaler.pkl', 'wb') as f:
  pkl.dump(df['Type'],f)

In [ ]:
ensemble_smote

VotingClassifier(estimators=[('Random forest classifier',
                              RandomForestClassifier(max_depth=5,
                                                     min_samples_leaf=9,
                                                     min_samples_split=5,
                                                     n_estimators=203,
                                                     random_state=100)),
                             ('Gradient Bossting Classifier',
                              GradientBoostingClassifier(learning_rate=0.07243118882864871,
                                                         max_depth=5,
                                                         min_samples_split=8,
                                                         n_estimators=230,
                                                         random_state=100,
                                                         subsample=0.995724756941474)),
                             ('AdaBoostclassifier',
                              AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=5,
                                                                                  min_samples_leaf=4,
                                                                                  min_samples_split=5,
                                                                                  random_state=100),
                                                 learning_rate=0.1,
                                                 n_estimators=200,
                                                 random_state=100))],
                 voting='soft')

In [ ]:
with open ('model_smote.pkl','rb')as file:
  ensemble_smote = pkl.load(file)

with open ('model_rose.pkl','rb')as file:
  ensemble_rose = pkl.load(file)

y_pred_smote = ensemble_smote.predict_proba(X_test)
y_pred_rose = ensemble_rose.predict_proba(X_test)

avr_proba = (y_pred_smote + y_pred_rose)/2
y_pred = np.argmax(avr_proba, axis =1)
#evaluation test data

accuracy = accuracy_score(y_test,y_pred)
precision = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)

#specificity
tn, fp, fn, tp = confusion_matrix(y_test,y_pred).ravel()
specificity = tn/(fp+tn)

# #roc curve
fpr,tpr,thershold = roc_curve(y_test, avr_proba[:,1])
auc_score = auc(fpr,tpr)

print('accuracy = ',accuracy)
print('precision = ',precision)
print('recall = ',recall)
print('specificity = ',specificity)
print('f1 = ',f1)
print('conf_matrix = ',conf_matrix)
print('auc_score = ',auc_score)

#training data testing

# print('Training Evaluation--------------------------------------------------------------------')
y_pred_train_smote = ensemble_smote.predict_proba(X_train)
y_pred_train_rose = ensemble_rose.predict_proba(X_train)

avr_proba_train = (y_pred_train_smote + y_pred_train_rose)/2
y_pred_train = np.argmax(avr_proba_train, axis =1)

# #evaluation train data

train_accuracy = accuracy_score(y_train,y_pred_train)
train_precision_score = precision_score(y_train,y_pred_train)
train_recall_score = recall_score(y_train,y_pred_train)
train_f1_score = f1_score(y_train,y_pred_train)
train_conf_matrix = confusion_matrix(y_train,y_pred_train)

#specificity
tn, fp, fn, tp = confusion_matrix(y_train,y_pred_train).ravel()
specificity_train = (tn/(fp+tn))

#roc curve
fpr,tpr,thershold = roc_curve(y_train, avr_proba_train[:,1])
roc_auc_train = auc(fpr, tpr)


print('train_accuracy',train_accuracy)
print('train_precision_score',train_precision_score)
print('train_recall_score',train_recall_score)
print('train_f1_score',train_f1_score)
print('train_conf_matrix',train_conf_matrix)
print('specificity_train: ',specificity_train)
print('roc_auc_train: ',roc_auc_train)

accuracy =  0.9888
precision =  0.8518518518518519
recall =  0.8117647058823529
specificity =  0.9950310559006211
f1 =  0.8313253012048193
conf_matrix =  [[2403   12]
 [  16   69]]
auc_score =  0.9802265253927658
train_accuracy 0.9997333333333334
train_precision_score 0.9921875
train_recall_score 1.0
train_f1_score 0.996078431372549
train_conf_matrix [[7244    2]
 [   0  254]]
specificity_train:  0.9997239856472536
roc_auc_train:  1.0


# **4. MULTI CLASS CLASSIFICATION FAILURE TYPE**

## **MODEL SELECTION**

In [ ]:
from imblearn.over_sampling import SMOTE

#logistic model
for model in models:
    print('------------------------------------------------------------------------------------')
    print('model name =', model)
    #model train
    X_sampled,y_sampled = RandomOverSampler().fit_resample(X_train,y_train)
    model.fit(X_sampled,y_sampled)

    # model prediction
    y_pred_test = model.predict(X_test)

    #model evaluation on test data
    accuracy = accuracy_score(y_test,y_pred_test)
    conf_matrix = confusion_matrix(y_test,y_pred_test)
    class_report = classification_report(y_test,y_pred_test)

    print('accuracy = ',accuracy)
    print('conf_matrix = ',conf_matrix)
    print('class_report = ',class_report)

    #training data testing

    print('Training Evaluation--------------------------------------------------------------------')
    y_pred_train = model.predict(X_train)

    # #evaluation train data

    train_accuracy = accuracy_score(y_train,y_pred_train)
    train_conf_matrix = confusion_matrix(y_train,y_pred_train)
    train_class_report = classification_report(y_train,y_pred_train)

    print('train_accuracy',train_accuracy)
    print('train_conf_matrix',train_conf_matrix)
    print('train_class_report = ',train_class_report)

------------------------------------------------------------------------------------
model name = KNeighborsClassifier(n_neighbors=9)
accuracy =  0.9435
conf_matrix =  [[  22    0    0    0    0    0]
 [  27 1835   19    6   12   31]
 [   0    2   14    0    0    0]
 [   1    3    1   14    0    0]
 [   0    4    0    0    0    0]
 [   0    7    0    0    0    2]]
class_report =                precision    recall  f1-score   support

           0       0.44      1.00      0.61        22
           1       0.99      0.95      0.97      1930
           2       0.41      0.88      0.56        16
           3       0.70      0.74      0.72        19
           4       0.00      0.00      0.00         4
           5       0.06      0.22      0.10         9

    accuracy                           0.94      2000
   macro avg       0.43      0.63      0.49      2000
weighted avg       0.97      0.94      0.96      2000

Training Evaluation-------------------------------------------------------

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


accuracy =  0.9915
conf_matrix =  [[  22    0    0    0    0    0]
 [   1 1928    0    0    0    1]
 [   0    3   13    0    0    0]
 [   0    0    0   19    0    0]
 [   0    4    0    0    0    0]
 [   0    8    0    0    0    1]]
class_report =                precision    recall  f1-score   support

           0       0.96      1.00      0.98        22
           1       0.99      1.00      1.00      1930
           2       1.00      0.81      0.90        16
           3       1.00      1.00      1.00        19
           4       0.00      0.00      0.00         4
           5       0.50      0.11      0.18         9

    accuracy                           0.99      2000
   macro avg       0.74      0.65      0.68      2000
weighted avg       0.99      0.99      0.99      2000

Training Evaluation--------------------------------------------------------------------
train_accuracy 1.0
train_conf_matrix [[  90    0    0    0    0    0]
 [   0 7722    0    0    0    0]
 [   0    0   62 

## **RECRUSIVE FEATURE ELEMINATION**

In [ ]:
for i in range(2,len(df.columns)+1):
  s = RFE(model,n_features_to_select=i).fit(X,y)
  l = []
  for i,value in enumerate(df.columns):
    if s.support_[i]:
      l.append(value)
  print(l)

  x = df[l]
  X_train,X_test,y_train,y_test = train_test_split(x,y, test_size = 0.20, random_state=100,stratify = y)

  model = GradientBoostingClassifier(random_state=100,)

  X_sampled,y_sampled = RandomOverSampler().fit_resample(X_train,y_train)
  model.fit(X_sampled,y_sampled)

  # model prediction
  y_pred_test = model.predict(X_test)

  #model evaluation on test data
  accuracy = accuracy_score(y_test,y_pred_test)
  conf_matrix = confusion_matrix(y_test,y_pred_test)
  class_report = classification_report(y_test,y_pred_test)

  print('accuracy = ',accuracy)
  print('conf_matrix = ',conf_matrix)
  print('class_report = ',class_report)
  print('-----------------------------------------------------------------------------------------------------------------------------------')

['Noise Power', 'Tool wear per Rotation']
accuracy =  0.7675
conf_matrix =  [[   6   14    1    0    0    1]
 [ 347 1492   10    0   14   67]
 [   1    0   15    0    0    0]
 [   0    0    0   19    0    0]
 [   1    2    0    0    0    1]
 [   0    5    1    0    0    3]]
class_report =                precision    recall  f1-score   support

           0       0.02      0.27      0.03        22
           1       0.99      0.77      0.87      1930
           2       0.56      0.94      0.70        16
           3       1.00      1.00      1.00        19
           4       0.00      0.00      0.00         4
           5       0.04      0.33      0.07         9

    accuracy                           0.77      2000
   macro avg       0.43      0.55      0.45      2000
weighted avg       0.97      0.77      0.85      2000

-----------------------------------------------------------------------------------------------------------------------------------
['Rotational speed [rpm]', 'Noise 

In [ ]:
"""['Rotational speed [rpm]', 'Noise Power', 'Difference Temperature', 'Tool wear per Rotation', 'Tool wear per power']
accuracy =  0.966
conf_matrix =  [[  22    0    0    0    0    0]
 [   2 1872   11    0    3   42]
 [   0    1   15    0    0    0]
 [   0    0    0   19    0    0]
 [   0    3    0    0    0    1]
 [   0    4    1    0    0    4]]
class_report =                precision    recall  f1-score   support

           0       0.92      1.00      0.96        22
           1       1.00      0.97      0.98      1930
           2       0.56      0.94      0.70        16
           3       1.00      1.00      1.00        19
           4       0.00      0.00      0.00         4
           5       0.09      0.44      0.14         9

    accuracy                           0.97      2000
   macro avg       0.59      0.73      0.63      2000
weighted avg       0.99      0.97      0.97      2000
"""

"""['Type', 'Air temperature [K]', 'Rotational speed [rpm]', 'Tool wear [min]', 'Noise Power', 'Difference Temperature', 'Torque per Rotation', 'Tool wear per Rotation', 'Tool wear per torque', 'Tool wear per power']
accuracy =  0.969
conf_matrix =  [[  22    0    0    0    0    0]
 [   2 1878    9    0    2   39]
 [   0    1   15    0    0    0]
 [   0    0    0   19    0    0]
 [   0    3    0    0    0    1]
 [   0    5    0    0    0    4]]
class_report =                precision    recall  f1-score   support

           0       0.92      1.00      0.96        22
           1       1.00      0.97      0.98      1930
           2       0.62      0.94      0.75        16
           3       1.00      1.00      1.00        19
           4       0.00      0.00      0.00         4
           5       0.09      0.44      0.15         9

    accuracy                           0.97      2000
   macro avg       0.60      0.73      0.64      2000
weighted avg       0.99      0.97      0.98      2000"""


In [ ]:
X = df.drop(columns = ['Unnamed: 0','UDI','Product ID','Target','Failure Type'])
X['Type'] = LabelEncoder().fit_transform(X['Type'])

label = LabelEncoder().fit(df['Failure Type'])
y = label.transform(df['Failure Type'])

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.25, random_state=100,stratify = y)

print(label.classes_)
print(len(X_train),len(X_test),len(y_train),len(y_test))

['Heat Dissipation Failure' 'No Failure' 'Overstrain Failure'
 'Power Failure' 'Random Failures' 'Tool Wear Failure']
7493 2498 7493 2498


In [ ]:
gbc = GradientBoostingClassifier(random_state =100,
                                learning_rate = 0.07243118882864871,
                                max_depth =  5,
                                min_samples_leaf = 1,
                                min_samples_split = 8,
                                n_estimators = 230,
                                subsample = 0.995724756941474)
X_sampled,y_sampled = SMOTE().fit_resample(X_train,y_train)
gbc.fit(X_sampled,y_sampled)
y_pred = gbc.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)
class_report = classification_report(y_test,y_pred)

print('accuracy = ',accuracy)
print('conf_matrix = ',conf_matrix)
print('class_report = ',class_report)

accuracy =  0.9679743795036029
conf_matrix =  [[  26    2    0    0    0    0]
 [   0 2348    5    0   17   41]
 [   0    2   18    0    0    0]
 [   0    0    0   24    0    0]
 [   0    3    0    0    0    1]
 [   0    9    0    0    0    2]]
class_report =                precision    recall  f1-score   support

           0       1.00      0.93      0.96        28
           1       0.99      0.97      0.98      2411
           2       0.78      0.90      0.84        20
           3       1.00      1.00      1.00        24
           4       0.00      0.00      0.00         4
           5       0.05      0.18      0.07        11

    accuracy                           0.97      2498
   macro avg       0.64      0.66      0.64      2498
weighted avg       0.99      0.97      0.98      2498



## **MODEL EVALUATION**

In [ ]:
df_multi_class = df[df['Target']==1]

X = df_multi_class.drop(columns = ['Unnamed: 0.1''Unnamed: 0','UDI','Product ID','Target','Failure Type'])
X['Type'] = LabelEncoder().fit_transform(X['Type'])

label = LabelEncoder().fit(df_multi_class['Failure Type'])
y = label.transform(df_multi_class['Failure Type'])

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.25, random_state=100,stratify = y)

print(label.classes_)
print(len(X_train),len(X_test),len(y_train),len(y_test))

['Heat Dissipation Failure' 'Overstrain Failure' 'Power Failure'
 'Tool Wear Failure']
247 83 247 83


In [ ]:
with open('FailureType.pkl','wb') as f:
  pkl.dump(df_multi_class['Failure Type'],f)

In [ ]:
gbc = GradientBoostingClassifier(random_state =100,
                                learning_rate = 0.07243118882864871,
                                max_depth =  5,
                                min_samples_leaf = 1,
                                min_samples_split = 8,
                                n_estimators = 230,
                                subsample = 0.995724756941474)
X_sampled,y_sampled = SMOTE().fit_resample(X_train,y_train)
MultiClassPredictor = gbc.fit(X_sampled,y_sampled)

print('TEST Evaluation--------------------------------------------------------------------')
y_pred = MultiClassPredictor.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)
class_report = classification_report(y_test,y_pred)

print('accuracy = ',accuracy)
print('conf_matrix = ',conf_matrix)
print('class_report = ',class_report)

print('Training Evaluation--------------------------------------------------------------------')
y_pred_train = MultiClassPredictor.predict(X_train)

# #evaluation train data

train_accuracy = accuracy_score(y_train,y_pred_train)
train_conf_matrix = confusion_matrix(y_train,y_pred_train)
train_class_report = classification_report(y_train,y_pred_train)

print('train_accuracy',train_accuracy)
print('train_conf_matrix',train_conf_matrix)
print('train_class_report = ',train_class_report)

TEST Evaluation--------------------------------------------------------------------
accuracy =  0.9879518072289156
conf_matrix =  [[28  0  0  0]
 [ 0 20  0  0]
 [ 0  0 24  0]
 [ 0  1  0 10]]
class_report =                precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       0.95      1.00      0.98        20
           2       1.00      1.00      1.00        24
           3       1.00      0.91      0.95        11

    accuracy                           0.99        83
   macro avg       0.99      0.98      0.98        83
weighted avg       0.99      0.99      0.99        83

Training Evaluation--------------------------------------------------------------------
train_accuracy 1.0
train_conf_matrix [[84  0  0  0]
 [ 0 58  0  0]
 [ 0  0 71  0]
 [ 0  0  0 34]]
train_class_report =                precision    recall  f1-score   support

           0       1.00      1.00      1.00        84
           1       1.00      1.00      1.

In [ ]:
with open('MultiClassModel.pkl', 'wb') as f:
  pkl.dump(MultiClassPredictor,f)